# To use:
#
#     pre-commit run -a
#
# Or:
#
#     pre-commit install  # (runs every time you commit in git)
#
# To update this file:
#
#     pre-commit autoupdate
#
# See https://github.com/pre-commit/pre-commit
#
# Based on:
# https://github.com/mpnunez/pybind11-conan-example/blob/a259bfe9bd99ded80f4bf16ce7c639e140f26408/.pre-commit-config.yaml
repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.8.0 # Use the appropriate version
    hooks:
      - id: golangci-lint
        # name: go lint and format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
#     -   id: end-of-file-fixer
#     -   id: trailing-whitespace
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
      - id: shellcheck