#!/bin/bash
set -e

read -p "This script will create terminal aliases for controlling smartthings devices. Do you really want to do this? (Y/n) " -n 1 -r

if [[ $REPLY =~ ^[Yy]$ ]]
then
    cp ./scripts/on-air ~
    cp ./scripts/off-air ~
    cp ~/.bash_profile ~/.bash_profile.before_onair # backup for good measure

    # TODO: this script should grab a working directory and echo it to the bash profile scripts
    echo "" >> ~/.bash_profile # newline for clarity
    echo "# Start OnAir Aliases" >> ~/.bash_profile
    echo 'alias onair="~/on-air"' >> ~/.bash_profile
    echo 'alias offair="~/off-air"' >> ~/.bash_profile
    echo "# End OnAir Aliases" >> ~/.bash_profile

    reset

    echo "The shortcuts 'onair' and 'offair' are now setup."
fi
