name: Unit Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
  
permissions:
  contents: read


jobs:
  golang-test:
    strategy:
      fail-fast: true
    runs-on: macos-latest
    steps:
      #----------------------------------------------
      # Check-out repo
      #----------------------------------------------
      - name: ⤵️ Check out repository
        uses: actions/checkout@v4
      #----------------------------------------------
      # Setup Go
      #----------------------------------------------
      - name: 🛠️ Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      # #----------------------------------------------
      # # Build
      # #----------------------------------------------
      # - name: 🏗️ Build
      #   run: go build -v ./...
      #----------------------------------------------
      # Run go tests
      #----------------------------------------------
      - name: 🧪 Run Go Tests
        uses: robherley/go-test-action@v0
        with:
          testArguments: -v ./...
